{
    'name': "Midland Custom Reports",
    'version': '19.0.0.1',
    'depends': ['base', 'sale', 'account', 'purchase', 'stock'],
    'data': [
        'reports/sale_order_report.xml',
        'reports/vendor_bill_report.xml',
        'reports/purchase_order_report.xml',
        'reports/packing_slip_report.xml',
        'reports/inovoice_report.xml',
        # 'reports/general_itmes_report.xml',
        'reports/payable_voucher_report.xml',
        'reports/good_recived_report.xml',
        # 'reports/delivery_note_report.xml',
        # 'reports/pick_list_report.xml',
        # 'reports/returns_report.xml',
        # 'reports/packing_labels_report.xml',
        # 'reports/batch_transfer_report.xml',
        # 'views/packing_view.xml',
        # 'views/res_company_views.xml',
        # 'views/good_recived_views.xml',
        # 'views/inovoice_view.xml',
        # 'views/batch_transfer_views.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
}
