# -*- coding: utf-8 -*-
{
    'name': "Real Estate",

    'summary': """
        Real Estate Management System.""",

    'description': """
        This module is developed to manage all the real estate operations.
    """,

    'author': "Wahab Ali Malik || Syed Hamza || Mudassir Ali Zaidi || Axiom Team",
    'website': "https://www.axiomworld.net",
    'category': 'Sales/Real Estate',
    'version': '19.0.1.0.3',
    'license': 'OEEL-1',
    'pre_init_hook': 'pre_init_hook',

    'depends': [
        'base',
        'mail',
        'portal',
        'crm',
        'default_payment',
    ],

    'data': [
        'security/rsms_security.xml',
        'security/ir.model.access.csv',
        # 'security/multi_company_rules.xml',
        'data/ir_sequence_data.xml',
        'data/product_data.xml',
        'data/automate_action.xml',
        'data/ir_actions_data.xml',
        'views/menuitems.xml',
        # 'views/res_users.xml',
        'views/res_config_setting.xml',
        'views/templates.xml',
        'views/account_invoice_ext.xml',
        'views/product_product_ext.xml',
        'views/product_realestate.xml',
        'views/ir_sequence.xml',
        'views/kin.xml',
        'views/cnic.xml',
        'views/members.xml',
        'views/file_transfer_request.xml',
        'views/file_transfer_application.xml',
        'views/file_refund.xml',
        'views/file_cancellation_application.xml',
        'views/file_search.xml',
        'views/change_installment_plan.xml',
        'views/file.xml',
        'views/file_payments.xml',
        'views/bulk_file_cancellation.xml',
        'views/ir_cron_ext.xml',
        # 'views/crm_lead_ext.xml',
        # 'views/validations.xml',
        # 'report/full_pay_greeting_letter.xml',
        # 'report/greeting_letter.xml',
        # 'report/transfer_request.xml',
        # 'report/transfer_letter.xml',
        # 'report/transfer_application.xml',
        # 'report/reminder_letter.xml',
        # 'report/forfeiture_notice.xml',
        # 'report/final_notice.xml',
        # 'report/template.xml',
        'views/price_list.xml',
        'views/preference_factor.xml',
        'views/required_documents.xml',
        'views/source.xml',
        'views/res_city.xml',
        'views/res_authority.xml',
        'views/location.xml',
        'views/unit_size.xml',
        'views/predefined_remarks.xml',
        'views/demarcated_area.xml',
        'views/plot_category.xml',
        'views/letters_report.xml',
        'views/file_attachment.xml',
        'wizard/create_inventory.xml',
        'wizard/plot_inventory_status.xml',
        'views/plot_inventory.xml',
        'views/sector.xml',
        'views/street.xml',
        'views/street_type.xml',
        'views/society.xml',
        'wizard/amount_knockoff.xml',
        'wizard/amount_adjust.xml',
        'wizard/import_data.xml',
        'views/file_merger.xml',
        'views/file_merger_application.xml',
        'views/unit_category_type.xml',
        'views/unit_class.xml',
        'views/create_invoice_file.xml',
        'views/advance_payments_file.xml',
        'views/account_payment_ext.xml',
        'views/members_check.xml',
        'views/predefine_plan.xml',
        'views/token_money.xml',
        'views/propose_plan.xml',
        'views/investment.xml',
        'views/investors.xml',
        'report/dealer_registration_report.xml',
        'views/res_investor.xml',
        'views/investor_payment.xml',
        'views/investor_file.xml',
        'views/legal_dispute.xml',
        'views/payment_interval.xml',
        'views/file_registry_request.xml',
        'views/required_taxes.xml',
        'views/unit_swapping_request.xml',
        'views/res_kin_request.xml',
        'wizard/token_money_validity_increase.xml',
        'wizard/token_refund.xml',
        'wizard/unit_swapping.xml',
        # 'report/installment.xml',
        'views/file_verification.xml',
        'views/file_installment_plan.xml',
        # 'views/file_charges_schedule.xml',
        'views/discount_policy.xml',
        'wizard/installment_invoice_wizard.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # 'real_estate/static/src/xml/*.xml',  # Legacy QWeb templates for followup (needs OWL rewrite)
            'real_estate/static/src/css/file_state.scss',
            'real_estate/static/src/css/form_custom_styles.css',
            'real_estate/static/src/css/followup.css',
            'real_estate/static/src/css/followup_summery.css',
            # 'real_estate/static/src/js/followup.js',  # Legacy odoo.define JS (needs OWL rewrite)
        ],
    },
}

